Robbie le pommie handle somerace conditions
DarkRiftNetworking/DarkRift pull request #147
Opened 2022-08-30 23:27 UTC by RobbieLePommie

As posted in https://github.com/DarkRiftNetworking/DarkRift/issues/146

2022-10-12 19:53 UTC, JamJar00 requested changes

2022-10-12 19:53 UTC, JamJar00 commented on DarkRift.Client/BichannelClientConnection.cs
> +            if (headerBuffer.Buffer?.Length > 3)
If we've got to `ProcessHeader` we aleady know we have 4 bytes so this is redundant

2022-10-12 19:53 UTC, JamJar00 commented on DarkRift.Server/ClientManager.cs
> +                logger.Info($"Handler for client [{client.ID}] is null. Enabling listener, but nothing is likely to happen.");
I like the addition of a warning here, it seems like a pretty silly thing for a user to be not doing!

Can we:
- Change this to a `warning` type log
- Change the wording to something a little more user-centric like 'Client [id] has connected but no plugin was subscribed to the ClientConnected event to process it. The client will still be connected'?
- Sort the formatting of the else keyword so it's on it's own line

Things like this are nice additions!

2022-10-12 19:53 UTC, JamJar00 commented on DarkRift.Server/Plugins/Listeners/Bichannel/BichannelServerConnection.cs
> +            if (headerBuffer.Buffer?.Length > 3)
As before

2022-10-12 21:34 UTC, RobbieLePommie commented on DarkRift.Server/ClientManager.cs
> +                logger.Info($"Handler for client [{client.ID}] is null. Enabling listener, but nothing is likely to happen.");
Ironically we had another developer encounter this yesterday, so I updated to make it clearer the plugin was not compiled. I'll amend when I next load the branch.

2022-11-17 06:14 UTC, RobbieLePommie commented on DarkRift.Server/ClientManager.cs
> +                logger.Info($"Handler for client [{client.ID}] is null. Enabling listener, but nothing is likely to happen.");
Just getting back to this: by "fixing" this, it has revealed another issue. If you have a plugin that has not yet loaded, but the app is listening, then a client can still connect but the plugin will not collect the messages still loading). If that happens, it appears impossible for a client to actually connect as the connection is "open". 

Solutions are:
 - ensure the plugin's listeners are loaded immediately, and queue messages in the plugin. Not ideal as it's still a race condition.

2022-12-20 13:40 UTC, 4real commented
I added a commit. I can't change the compare branch on this PR for some reason so I'm moving over to #163

2022-12-20 13:40 UTC, closed without merging